### ISSUE TITLE
About training comsuption.

### ISSUE THREAD

**Issue by OliverHxh** [PKU-YuanGroup/Video-LLaVA#11]
Dear authors,

Thanks for your great work, which is of great value to the community. 

I would like to know how many GPUs (what type) you use to train the network. And roughly training time?

I am looking forward to hearing back from you.

Best

**Comment by LinB203** [comment]
Thanks for your attention. For the first stage, approximately 2 days are required, and an additional 2 days are needed for the second stage. Each stage utilizes 4 PCIE A100-80G.

Furthermore, it is worth mentioning that the current speed is considered slow due to the absence of compressed video tokens. However, we are working on developing a new and powerful version, which we anticipate will yield significant improvements. Please stay tuned.
