### ISSUE TITLE
[Dataset] Is it possible to provide a download link of processed data besides baidu nextdisk?

### ISSUE THREAD

**Issue by TousakaNagio** [PKU-YuanGroup/Video-LLaVA#23]
Thank you for the great work. Is it possible to provide a download link of processed data besides baidu nextdisk?

**Comment by LinB203** [comment]
Sorry, due to limited storage, we have no way to upload to Google Cloud or others. You can download them from the original repository according to the path of the instructions, e.g. image from LLaVA. And then make the corresponding format according to the annotation we released (just need to change the path).
