### ISSUE TITLE
在online demo上传长视频时网页报错

### ISSUE THREAD

**Issue by allex083** [PKU-YuanGroup/Video-LLaVA#91]
我在online demo上传一个比较长（几十分钟，七八百MB，想让模型描述该视频）的视频时网页报错。想咨询一下，Video-LLaVA是否有视频长度的限制？还是网页端做的限制？

Video-LLaVA是否可用于长视频的理解？

**Comment by LinB203** [comment]
目前没有视频长度的限制。然而，我认为Video-LLaVA针对长视频的理解可能表现不佳。因为它是依靠均匀抽取8帧的理解。对于长视频的理解，我推荐你尝试Chat-UniVi，它采用更多的帧进行理解视频。


[En] There is currently no video length limit. However, I think Video-LLaVA's comprehension for long videos may not perform well. This is because it relies on an even extraction of 8 frames for comprehension. For long video comprehension, I recommend you try Chat-UniVi, which uses more frames for comprehending the video.


https://github.com/PKU-YuanGroup/Chat-UniVi

**Comment by allex083** [comment]
如果没有视频长度的限制，为什么上传长视频后网页会报错呢？这个问题可以解决吗？我想试试看。

也感谢您的推荐Chat-UniVi。

**Comment by LinB203** [comment]
这个原因暂时不明确，因为模型是挂在到huggingface的。这意味着可能受限于huggingface给定的虚拟环境的配置。你可以按照readme把模型下载到本地进行推理。

[En] The reason for this is not clear at the moment, as the model is hooked up to the huggingface. This means that it may be limited by the configuration of the virtual environment given by huggingface. You can follow the readme to download the model locally for inference.

**Comment by allex083** [comment]
好的，我本地部署试试看。

Chat-UniVi也是基于video-llava的吗？
